# Generated by Django 5.2.2 on 2025-06-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_artikel_bild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artikel",
            name="bild",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
