# Generated by Django 5.2.2 on 2025-06-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_artikel_bild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bestellung",
            name="auftrags_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
