# Generated by Django 5.2.2 on 2025-06-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_bestellung_auftrags_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artikel",
            name="preis",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="kunde",
            name="email",
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
