# Generated by Django 5.2.2 on 2025-06-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_artikel_preis_alter_kunde_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artikel",
            name="bild",
            field=models.ImageField(blank=True, null=True, upload_to="artikelbilder/"),
        ),
    ]
